### ISSUE TITLE
New op_edit for Max GAS allow 

### ISSUE THREAD

**Issue by chicman** [sshane/openpilot#423]
Stock OP would behave varies on different cars, but I know most cars has the long control issues.

One of my suggestion is to add a new op_edit option, which will limit the MAX Gas would allowed under any situation.
100% is full gas, 50% is half.

This would improve the OP experience with a lot smoother long control.

**Comment by sshane** [comment]
What car do you have? Can you share a dongle id?

**Comment by sshane** [comment]
Closed for inactivity
