### ISSUE TITLE
HTTP Error 400 when trying to pair with Connect

### ISSUE THREAD

**Issue by mittsquared** [sshane/openpilot#427]
Hi there,

I've been using Stock Additions for a couple months without issues on my '19 Prius (comma two purchased new in late April or early May).
This past weekend, however, Connect has started to show as Offline with a yellow indicator on data (Connect comes back online only on WiFi).
Also, my device has been unpaired from my account and will not repair using the app, resulting in an HTTP 400 error code when scanning the QR code.
Are there any thoughts as to why this has stopped working suddenly?
I would like to try anything I can while on SA before switching to stock (since switching takes some time).

Thank you!

**Comment by sshane** [comment]
Sounds like an issue that should be posting to commaai/openpilot
