### ISSUE TITLE
`upload_on_hotspot` does nothing

### ISSUE THREAD

**Issue by khoi** [sshane/openpilot#496]
**Describe the bug**
https://github.com/sshane/openpilot/blob/210da470fc78cce48f38691c2e355727f24e5bc2/selfdrive/loggerd/uploader.py#L30

the variable is set but I don't see it's being used anywhere?

**Comment by sshane** [comment]
You're right, missed removing it. In Android 12 (and 11?) you can't detect if you're on a hotspot based on IP alone as they're randomized, so it makes it difficult to keep up with this. Will remove unless I find another way to detect hotspot

**Comment by sshane** [comment]
#503

**Comment by sshane** [comment]
Should be fixed by #503
