### ISSUE TITLE
Sentry tripped while car is already in an unlocked state

### ISSUE THREAD

**Issue by bensonkwek** [sshane/openpilot#557]
To reproduce

Scenario 1
- car is in locked state
- unlock car
- enter car , shut the door
- wait for a min
- open door

Scenario 2
- car is in unlocked state
- enter car , shut the door

Result : sentry warning tripped

Vid: https://streamable.com/kqchpa

Hybrid RAV4 2021

Let me know what other information you need

**Comment by sshane** [comment]
The problem is I want it to arm after being inactive for a bit as I don't have the lock signals for other cars coded. I can raise the timer to 5 minutes though if that'll help. Right now it's only 2 minutes

**Comment by Asherlc** [comment]
Same issue for me, would it be possible to enable the timer only for unsupported cars?

**Comment by sshane** [comment]
Another problem is if you start the C3 while the car is already locked, it has no idea what the lock status is, as it's only published when it changes when the car is off. Feel free to make a PR to make it easy to stop the alarm if it's a verified user, or raise the timeout.
